services:
  postgres:
    image: postgres:14
    container_name: ema_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_staff
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
